version: 2
jobs:
  build:
    docker:
      - image: bitwalker/alpine-elixir:1.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependency-cache-{{ checksum "mix.lock" }}
            - v3-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run:
          command: mix deps.compile
          environment:
            MIX_ENV: test
      - run: mix dialyzer --plt
      - save_cache:
          key: v3-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - save_cache:
          key: v3-dependency-cache
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix dialyzer --halt-exit-status
      - run: mix coveralls.circle
